TGT_CFLAGS	+= -I.
TGT_CXXFLAGS	+= -I.

BINARY		= tests
SRCFILES	= shell.c tests.c

SRC_EXT = c

# tool macros
CC := gcc
CCFLAG := -std=c99 -I. -DUNITTEST
DBGFLAG := -g
CCOBJFLAG := $(CCFLAG) -c
LDFLAGS := -lc -lgcc

# path macros
BIN_PATH := bin
OBJ_PATH := obj
SRC_PATH := src
DBG_PATH := debug

# compile macros
TARGET_NAME := tests
TARGET := $(TARGET_NAME)
MAIN_SRC := tests.c

OBJS = $(SRCFILES:%.$(SRC_EXT)=%.o)
DEPS = $(OBJECTS:.o=.d)

# default rule
default: all

# non-phony targets
$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $@
	./$(TARGET)

%.o: %.c*
	echo $(CCOBJFLAG)
	$(CC) $(CCOBJFLAG) -o $(*).o -c $(*).c

# phony rules
.PHONY: all
all: $(TARGET)
